name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6 
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.8 
  url_strategy: ^0.2.0   
  pin_code_fields: ^7.3.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.3.2
  flutter_typeahead: ^4.0.0
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  image_picker_ios: ^0.8.5+6
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  flutter_inappwebview: ^5.4.3+7
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.2
  http: ^0.13.4
  intl: ^0.17.0
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.1
#  google_sign_in: ^5.2.1
#  flutter_facebook_auth: ^3.5.7
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+1
  share_plus: ^4.0.10
  fwfh_text_style: ^2.22.8+1
  expandable_bottom_sheet: ^1.1.1+1
  flutter_rating_bar: ^4.0.1
  dots_indicator: ^2.1.0
  image_cropper: ^3.0.0
  dotted_line: ^3.1.0
  table_calendar: ^2.1.0 
  date_picker_timeline: ^1.2.3
  im_stepper: ^1.0.1+1
  file_picker: ^5.2.4




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900